version: '3'

services:
    app:
        depends_on:
            - 'box'
        build: .
        command: bash start.sh
        ports: 
            - 3000:3000
        volumes: 
            - '.:/onebitinsta_api'
            - 'box:/box'
        environment: 
            - BUNDLE_PATH=/box
        stdin_open: true
        tty: true

    box:
        image: busybox
        volumes: 
            - box:/box

volumes: 
    box: